api/urls.py
from django.conf.urls import include
from django.urls import path
from rest_framework.authtoken import views as drf_views
from rest_framework.routers import DefaultRouter

from hotspots import views as hostpot_views
from hypothesis import views as hypo_views
from scoring import views as score_views
from viewer import views as viewer_views

router = DefaultRouter()
# Register the basic data
router.register("compounds", viewer_views.CompoundView, "compounds")
router.register("targets", viewer_views.TargetView, "targets")
router.register("projects", viewer_views.ProjectView)
router.register("session-projects", viewer_views.SessionProjectView)
router.register("snapshots", viewer_views.SnapshotView)
router.register("action-type", viewer_views.ActionTypeView)
router.register("session-actions", viewer_views.SessionActionsView)
router.register("snapshot-actions", viewer_views.SnapshotActionsView)
router.register("compound-identifier-types", viewer_views.CompoundIdentifierTypeView)
router.register("compound-identifiers", viewer_views.CompoundIdentifierView)

# Compounds sets
router.register("compound-sets", viewer_views.ComputedSetView)
router.register("compound-molecules", viewer_views.ComputedMoleculesView)
router.register("numerical-scores", viewer_views.NumericalScoreValuesView)
router.register("text-scores", viewer_views.TextScoresView)
router.register("compound-scores", viewer_views.CompoundScoresView, "compound-scores")
router.register(
    "compound-mols-scores", viewer_views.ComputedMolAndScoreView, "compound-mols-scores"
)

# Get the derived data
router.register("molimg", viewer_views.MolImageView, "molimg")
router.register("vector", viewer_views.VectorsView, "vector")
router.register("graph", viewer_views.GraphView, "graph")
router.register("cmpdimg", viewer_views.CompoundImageView, "cmpdimg")
router.register("protmap", viewer_views.ProteinMapInfoView, "protmap")
router.register("protpdb", viewer_views.ProteinPDBInfoView, "protpdb")
router.register("protpdbbound", viewer_views.ProteinPDBBoundInfoView, "protpdbbound")
router.register("molprops", viewer_views.MolecularPropertiesView, "molprops")

# Hotspot maps
router.register("hotspots", hostpot_views.HotspotView)

# Register the vectors and hypothesis
router.register("interactions", hypo_views.InteractionView)
router.register("targetres", hypo_views.TargetResidueView)
router.register("interactionpoints", hypo_views.InteractionPointView)

# Register the  choices
router.register("scorechoice", score_views.ScoreChoiceView)
router.register("siteobservationchoice", score_views.SiteObservationChoiceView)
router.register("cmpdchoice", score_views.CmpdChoiceView)

# Register the scenese
router.register("viewscene", score_views.ViewSceneView)

# Register the groups
router.register("siteobservationgroup", score_views.SiteObservationGroupView)

# Get the information
router.register("siteobservationannotation", score_views.SiteObservationAnnotationView)

# discourse posts
router.register(
    "discourse_post", viewer_views.DiscoursePostView, basename='discourse_post'
)

# Take a dictionary and return a csv
router.register("dicttocsv", viewer_views.DictToCSVView, basename='dicttocsv')

# tags
router.register("tag_category", viewer_views.TagCategoryView, basename='tag_category')
router.register(
    "siteobservation_tag",
    viewer_views.SiteObservationTagView,
    basename='siteobservation_tag',
)
router.register(
    "session_project_tag",
    viewer_views.SessionProjectTagView,
    basename='session_project_tag',
)

# Download a zip file of the requested contents
router.register(
    "download_structures",
    viewer_views.DownloadStructuresView,
    basename='download_structures',
)

# Experiments and Experiment (XChemAlign) upload support
router.register(
    "upload_target_experiments",
    viewer_views.UploadExperimentUploadView,
    basename='upload_target_experiments',
)
router.register(
    "download_target_experiments",
    viewer_views.DownloadExperimentUploadView,
    basename='download_target_experiments',
)


router.register(
    "target_experiment_uploads",
    viewer_views.ExperimentUploadView,
    basename='target_experiment_uploads',
)
router.register(
    "site_observations", viewer_views.SiteObservationView, basename='site_observations'
)
router.register("canon_sites", viewer_views.CanonSiteView, basename='canon_sites')
router.register("experiments", viewer_views.ExperimentView, basename='experiments')
router.register(
    "canon_site_confs", viewer_views.CanonSiteConfView, basename='canon_site_confs'
)
router.register(
    "xtalform_sites", viewer_views.XtalformSiteView, basename='xtalform_sites'
)
router.register("poses", viewer_views.PoseView, basename='poses')
router.register(
    "metadata_upload", viewer_views.UploadMetadataView, basename='metadata_upload'
)
router.register(
    "computedset_download",
    viewer_views.DownloadComputedSetView,
    basename='computedset_download',
)

# Squonk Jobs
router.register(
    "job_file_transfer", viewer_views.JobFileTransferView, basename='job_file_transfer'
)
router.register("job_callback", viewer_views.JobCallBackView, basename='job_callback')
router.register("job_config", viewer_views.JobConfigView, basename='job_config')
router.register("job_override", viewer_views.JobOverrideView, basename='job_override')


from rest_framework import response, schemas
from rest_framework.decorators import api_view, renderer_classes
from rest_framework_swagger.renderers import OpenAPIRenderer, SwaggerUIRenderer


@api_view()
@renderer_classes([SwaggerUIRenderer, OpenAPIRenderer])
def schema_view(request):
    _ = request.build_absolute_uri()
    generator = schemas.SchemaGenerator(title="Fragalysis API")
    return response.Response(generator.get_schema(request=request))


urlpatterns = [
    path("", include(router.urls)),
    path("auth/", drf_views.obtain_auth_token, name="auth"),
    path("swagger/", schema_view),
    path("job_request/", viewer_views.JobRequestView.as_view(), name="job_request"),
]

fragalysis/urls.py
import mozilla_django_oidc.views
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from graphene_django.views import GraphQLView

import fragalysis.views

urlpatterns = [
    re_path(r"^$", RedirectView.as_view(url="/viewer/react/landing")),
    path("version/", fragalysis.views.version, name="version"),
    path("admin/", admin.site.urls),
    path("viewer/", include("viewer.urls")),
    path("network/", include("network.urls")),
    path("api/", include("api.urls")),
    path("media/", include("media_serve.urls")),
    path("scoring/", include("scoring.urls")),
    path("graphql/", GraphQLView.as_view(graphiql=True)),
    path('oidc/', include('mozilla_django_oidc.urls')),
    path(
        "accounts/login/",
        mozilla_django_oidc.views.OIDCAuthenticationRequestView.as_view(),
        name="keylcoak_login",
    ),
    path(
        "accounts/logout/",
        fragalysis.views.LogoutView.as_view(),
        name="keycloak_logout",
    ),
    path(
        "oidc/callback/",
        mozilla_django_oidc.views.OIDCAuthenticationCallbackView.as_view(),
        name="keycloak_callback",
    ),
    path("", include("django_prometheus.urls")),
]

viewer/urls.py
from django.urls import path, re_path

from . import views

app_name = 'viewer'

urlpatterns = [
    re_path(r"^react/*", views.react, name="react"),
    path("upload_cset/", views.UploadComputedSetView.as_view(), name="upload_cset"),
    path(
        "validate_task/<uuid:validate_task_id>/",
        views.ValidateTaskView.as_view(),
        name="validate_task",
    ),
    path(
        "upload_task/<uuid:upload_task_id>/",
        views.UploadTaskView.as_view(),
        name="upload_task",
    ),
    path(
        "update_task/<uuid:update_task_id>/",
        views.UpdateTaskView.as_view(),
        name="update_task",
    ),
    path("img_from_smiles/", views.img_from_smiles, name="img_from_smiles"),
    path("highlight_mol_diff/", views.highlight_mol_diff, name="highlight_mol_diff"),
    path("open_targets/", views.get_open_targets, name="get_open_targets"),
    path("upload_designs/", views.DesignSetUploadView.as_view(), name="upload_designs"),
    path("job_access/", views.JobAccessView.as_view(), name="job_access"),
    path(
        "task_status/<uuid:task_id>/",
        views.TaskStatusView.as_view(),
        name="task_status",
    ),
    path("service_state/", views.ServiceStateView.as_view(), name="service_state"),
]

viewer/forms.py
from django import forms

CSET_CHOICES = [
    ('V', 'Validate'),
    ('U', 'Upload'),
    ('D', 'Delete'),
]

TSET_CHOICES = [
    ('V', 'Validate'),
    ('U', 'Upload'),
]


class CSetForm(forms.Form):
    """Used for uploading Computed sets at viewer/upload_cset"""

    proposal_ref = forms.CharField(required=False, label='Proposal', max_length=200)
    target_name = forms.CharField(label='Target', max_length=100, required=False)
    sdf_file = forms.FileField(label='All compounds sdf (.sdf)', required=False)
    pdb_zip = forms.FileField(label='PDB files (.zip)', required=False)
    submit_choice = forms.CharField(widget=forms.RadioSelect(choices=CSET_CHOICES))
    # The upload_key was removed as part of development if issue-859,
    # the phase 2 Job launcher,
    # The user-specific 'upload_key' is/was key generated by `viewer.views.cset_key`

viewer/templates/viewer/generate-key.html
{% load static %}

{% block content %}
    <h1>Compound set upload key</h1>
    <h2>Instructions</h2>
    <p>Enter your email address below. Your upload key will be emailed to you. If you lose your upload key, please email rachael.skyner@diamond.ac.uk to retrieve it</p>
    <br>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit</button>
  </form>
   {% autoescape off %}
       {{ message }}
   {% endautoescape %}



{% endblock %}

viewer/templates/viewer/react_temp.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
 <head>
     <link rel="stylesheet" href="https://bootswatch.com/3/simplex/bootstrap.min.css" crossorigin="anonymous">
 <meta charset="UTF-8">
 <title>XChem @ Diamond</title>
 </head>
 <body>
 {% csrf_token %}
 <div id="app"></div>


 <script type="text/javascript">

 {% if user.is_authenticated %}
     var DJANGO_CONTEXT ={
         {% if target_warning_message %}
         target_warning_message: '{{ target_warning_message }}',
         {% endif %}
         legacy_url: '{{ legacy_url }}',
         username: '{{ user.username }}',
         email: '{{ user.email|default:"noemail" }}',
         pk: {{user.pk|default:-1}},
         authenticated: true,
         discourse_available: {{ discourse_available }},
         user_present_on_discourse: {{ user_present_on_discourse|default:"false" }},
         discourse_host: '{{ discourse_host }}',
         squonk_available: {{ squonk_available }},
         squonk_ui_url: '{{ squonk_ui_url }}'
     }
 {% else %}
     var DJANGO_CONTEXT = {
         {% if target_warning_message %}
         target_warning_message: '{{ target_warning_message }}',
         {% endif %}
         legacy_url: '{{ legacy_url }}',
         username: 'NOT_LOGGED_IN',
         email: "noemail",
         pk: undefined,
         authenticated: false,
         discourse_available: {{ discourse_available }},
         squonk_available: {{ squonk_available }}
     }
 {% endif %}

</script>

 {% render_bundle 'main' %}
 </body>
</html>

viewer/templates/viewer/upload-cset.html
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Compound set upload</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
  <script src="https://cdn.jsdelivr.net/npm/vue"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>
{% block content %}
    <body>
      <section class="hero is-primary has-background-grey">
        <div class="hero-body">
{#          <div class="container">#}
            <h1 class="title is-size-1 has-text-centered">Compound Set Upload</h1>
            <p class="subtitle has-text-centered" id="progress-title"></p>
        </div>
        </section>
      <section class="hero is-light has-background-white">
        <div class="hero-body">
            <div class="columns is-centered">
              <div class="column is-8" id="content">
                  <p>
                      Here, you can upload compound sets for follow up compounds (computed 3D coordinates)
                      The current instructions are here:
                      <a href="https://discuss.postera.ai/t/providing-computed-poses-for-others-to-look-at/1155">postera forum</a>
                  </p>
                  <br>
                  <p>The current specification version is <b>ver_1.2</b></p>
                  <br>
                  <form method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{ form.as_ul }}
                      <label for="{{ sets.id_for_label }}" class="col-sm-2 control-label">Update/delete existing set:</label>
                      <div class="col-sm-10">
                        <select name="update_set" class="form-control">
                          <option value="None" selected>None</option>
                          {% for set in sets %}
                          <option value="{{ set.name }}">{{ set.name }}</option>
                          {% endfor %}
                        </select>
                      </div>
                    <button type="submit">Submit</button>
                </form>

                {# We may have been given an error from the previous attmept #}
                {# For example the user may have selected 'DELETE' but not selected a prior set #}
                {# if this is so we'll get a 'session_error' which we print with #}
                {# a suitable "oops!" prefix. #}
                {% if session_error %}
                <p style="color:red;"><strong>Oops!</strong> {{ session_error }}</p>
                {% endif %}

                {# We may have been given a message from the previous attmept #}
                {# For example the user may have selected 'DELETE' and this is the confirmation #}
                {% if session_message %}
                <p style="color:blue;">{{ session_message }}</p>
                {% endif %}

                {% autoescape off %}
                  {% if download_url %}
                    {{ download_url }}
                  {% endif %}
                  {% if table %}
                    {{ table }}
                  {% endif %}
                {% endautoescape %}
              </div>
            </div>
          </div>
      </section>
        <p class="has-text-centered" id="links"></p>
        <p class="has-text-centered" id="validate-id"></p>
        <p class="has-text-centered" id="upload-id"></p>
    </body>

    {% if error_message %}
    <script>
      var content = document.getElementById('content');
      content.innerHTML = "";
      var content = document.getElementById('links');
      content.innerHTML = "{{ error_message }}";
    </script>
    {% endif %}

    {% if validate_task_id %}
          <script>
          var content = document.getElementById('content');
          content.innerHTML = "";
          var taskUrl = "{% url 'viewer:validate_task' validate_task_id=validate_task_id %}";
          var validid = document.getElementById('validate-id');
          validid.innerHTML = taskUrl;
          var dots = 1;
          var progressTitle = document.getElementById('progress-title');
          updateProgressTitleVal();
          var timerVal = setInterval(function() {
            updateProgressTitleVal();
            axios.get(taskUrl)
              .then(function(response){
                var taskStatus = response.data.validate_task_status;
                if (taskStatus === 'SUCCESS') {

                  var content = document.getElementById('links');
                  content.innerHTML = response.data.html;

                  clearTimerVal('');
                }

                else if (taskStatus === 'FAILURE') {

                    clearTimerVal('An error occurred - see traceback below');
                    var content = document.getElementById('links');
                    content.innerHTML = response.data.validate_traceback;

                }
              })
          }, 800);

          function updateProgressTitleVal() {
            dots++;
            if (dots > 3) {
              dots = 1;
            }
            progressTitle.innerHTML = 'validating files';
            for (var i = 0; i < dots; i++) {
              progressTitle.innerHTML += '.';
            }
          }
          function clearTimerVal(message) {
            clearInterval(timerVal);
            progressTitle.innerHTML = message;
          }
         </script>
    {% endif %}

    {% if upload_task_id %}
          <script>
          var content = document.getElementById('content');
          content.innerHTML = "";
          var taskUrl = "{% url 'viewer:upload_task' upload_task_id=upload_task_id %}";
          var validid = document.getElementById('upload-id');
          validid.innerHTML = taskUrl;
          var dots = 1;
          var progressTitle = document.getElementById('progress-title');
          updateProgressTitle();
          var timer = setInterval(function() {
            updateProgressTitle();
            axios.get(taskUrl)
              .then(function(response) {
                  var taskStatus = response.data.upload_task_status;
                  if (taskStatus === 'SUCCESS') {
                      var validatedStatus = response.data.validated;
                      if (validatedStatus === 'Not validated') {

                          var content = document.getElementById('links');
                          content.innerHTML = response.data.html;

                          clearTimer('');

                      }
                      if (validatedStatus === 'Validated') {
                          clearTimer('Your files were uploaded! The download links are:');

                          var url_a = response.data.results.cset_download_url;
                          var content = document.getElementById('links');
                          var a = document.createElement("a");
                          var link = document.createTextNode("    Compound Set    ");
                          a.appendChild(link);
                          a.title = 'compound set';
                          a.href = url_a;
                          content.appendChild(a);

                          var br = document.createElement('br');
                          content.appendChild(br);

                          var url_b = response.data.results.pset_download_url;
                          var b = document.createElement("a");
                          var link_b = document.createTextNode("    Protein Set    ");
                          b.appendChild(link_b);
                          b.title = 'protein set';
                          b.href = url_b;
                          content.appendChild(b);

                      }
                      var moleculesProcessed = response.data.processed;

                      if (moleculesProcessed === 'None') {

                          var content = document.getElementById('links');
                          content.innerHTML = response.data.html;

                          clearTimer('');

                      }
                  }
                    else if (taskStatus === 'FAILURE') {

                        clearTimer('An error occurred - see traceback below');
                        var content = document.getElementById('links');
                        content.innerHTML = response.data.upload_traceback;

                }
              })
          }, 800);

          function updateProgressTitle() {
            dots++;
            if (dots > 3) {
              dots = 1;
            }
            progressTitle.innerHTML = 'processing uploaded files';
            for (var i = 0; i < dots; i++) {
              progressTitle.innerHTML += '.';
            }
          }
          function clearTimer(message) {
            clearInterval(timer);
            progressTitle.innerHTML = message;
          }
         </script>
    {% endif %}

{% endblock %}

viewer/templates/viewer/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload files</title>
    {% block javascript %}
  {# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>
<script>
$(function () {

  $(".js-upload-photos").click(function () {
    $("#fileupload").click();
  });

  $("#fileupload").fileupload({
    dataType: 'json',
    sequentialUploads: true,  /* 1. SEND THE FILES ONE BY ONE */
    start: function (e) {  /* 2. WHEN THE UPLOADING PROCESS STARTS, SHOW THE MODAL */
      $("#modal-progress").modal("show");
    },
    stop: function (e) {  /* 3. WHEN THE UPLOADING PROCESS FINALIZE, HIDE THE MODAL */
      $("#modal-progress").modal("hide");
    },
    progressall: function (e, data) {  /* 4. UPDATE THE PROGRESS BAR */
      var progress = parseInt(data.loaded / data.total * 100, 10);
      var strProgress = progress + "%";
      $(".progress-bar").css({"width": strProgress});
      $(".progress-bar").text(strProgress);
    },
    done: function (e, data) {
      if (data.result.is_valid) {
        $("#gallery tbody").prepend(
                // Here we show thumbnail of prottein and link to view it
          "<tr><td><a href='" + data.result.url + "'>" + data.result.name + "</a></td></tr>"
        )
      }
    }

  });

});
</script>
{% endblock %}

</head>
<body>

<div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Uploading...</h4>
      </div>
      <div class="modal-body">
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="well text-muted text-center" style="padding-top: 4rem; padding-bottom: 4rem;">
  <span class="glyphicon glyphicon-arrow-down" style="font-size: 4rem;"></span>
  <h3>Drop Photos Here to Upload</h3>
</div>


{# 1. BUTTON TO TRIGGER THE ACTION #}
<button type="button" class="btn btn-primary js-upload-photos">
  <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos
</button>

{# 2. FILE INPUT TO BE USED BY THE PLUG-IN #}
<input id="fileupload" type="file" name="file" multiple
       style="display: none;"
       data-url="{% url 'viewer:upload' %}"
       data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

{# 3. TABLE TO DISPLAY THE UPLOADED PHOTOS #}
<table id="gallery" class="table table-bordered">
  <thead>
    <tr>
      <th>Photo</th>
    </tr>
  </thead>
  <tbody>
    {% for photo in photos %}
      <tr>
        <td><a href="{{ photo.file.url }}">{{ photo.file.name }}</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>

</body>
</html>